# Generated by Django 5.1.7 on 2025-05-02 08:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic_main', '0002_school'),
    ]

    operations = [
        migrations.AddField(
            model_name='activeterm',
            name='school',
            field=models.OneToOneField(default='2', on_delete=django.db.models.deletion.CASCADE, related_name='active_term', to='academic_main.school'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='term',
            name='school',
            field=models.ForeignKey(default='2', on_delete=django.db.models.deletion.CASCADE, related_name='terms', to='academic_main.school'),
            preserve_default=False,
        ),
    ]
