# Generated by Django 5.2.1 on 2025-05-18 14:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic_main', '0003_activeterm_school_term_school'),
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolPaymentInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('flutterwave', 'Flutterwave'), ('paystack', 'Paystack'), ('monify', 'Monify'), ('bank_transfer', 'Bank Transfer')], max_length=20)),
                ('account_name', models.CharField(blank=True, max_length=255, null=True)),
                ('account_number', models.CharField(blank=True, max_length=50, null=True)),
                ('bank_name', models.CharField(blank=True, max_length=255, null=True)),
                ('provider_account_id', models.CharField(blank=True, max_length=255, null=True)),
                ('provider_secret_key', models.CharField(blank=True, max_length=255, null=True)),
                ('metadata', models.JSONField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_methods', to='academic_main.school')),
            ],
        ),
    ]
