# Generated by Django 5.1.7 on 2025-04-25 20:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stu_main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='form_master',
            field=models.ForeignKey(blank=True, limit_choices_to={'user_type': 'teacher'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='form_master_classes', to=settings.AUTH_USER_MODEL),
        ),
    ]
