# Generated by Django 5.1.7 on 2025-04-25 21:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stu_main', '0003_classsubject_created_by_alter_classsubject_subject'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classsubject',
            name='created_by',
        ),
        migrations.AddField(
            model_name='studentpost',
            name='created_by',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, related_name='created_posts', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='studentpost',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='stu_main.student'),
        ),
    ]
