# Generated by Django 5.1.7 on 2025-04-25 21:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stu_main', '0004_remove_classsubject_created_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentpost',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_posts', to=settings.AUTH_USER_MODEL),
        ),
    ]
