# Generated by Django 5.1.7 on 2025-05-03 21:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic_main', '0003_activeterm_school_term_school'),
        ('stu_main', '0005_alter_studentpost_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='school',
            field=models.ForeignKey(default='2', on_delete=django.db.models.deletion.CASCADE, related_name='classes', to='academic_main.school'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subject',
            name='school',
            field=models.ForeignKey(default='2', on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='academic_main.school'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[('admin', 'Admin'), ('principal', 'Principal'), ('teacher', 'Teacher'), ('student', 'Student')], default='principal', max_length=10),
        ),
        migrations.AlterUniqueTogether(
            name='class',
            unique_together={('name', 'school')},
        ),
    ]
