# Generated by Django 5.1.7 on 2025-05-03 21:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic_main', '0003_activeterm_school_term_school'),
        ('stu_main', '0006_class_school_subject_school_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentpost',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='academic_main.school'),
        ),
    ]
