# Generated by Django 5.1.7 on 2025-05-04 07:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stu_main', '0009_teacher'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classsubject',
            name='teacher',
            field=models.ForeignKey(default='3', on_delete=django.db.models.deletion.CASCADE, related_name='class_subjects', to='stu_main.teacher'),
            preserve_default=False,
        ),
    ]
