# Generated by Django 5.2.1 on 2025-05-16 17:25

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stu_main', '0013_remove_student_guardians_student_date_of_birth_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='registration_number',
            field=models.UUIDField(default=uuid.uuid4, editable=False, null=True),
        ),
    ]
