# Generated by Django 5.2.1 on 2025-05-16 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stu_main', '0014_student_registration_number'),
    ]

    operations = [
    ]
from django.db import migrations
import uuid

def generate_registration_numbers(apps, schema_editor):
    Student = apps.get_model('stu_main', 'Student')
    for student in Student.objects.all():
        student.registration_number = uuid.uuid4()
        student.save()

class Migration(migrations.Migration):

    dependencies = [
        ('stu_main', '0014_student_registration_number'),  # Replace with your actual previous migration
    ]

    operations = [
        migrations.RunPython(generate_registration_numbers),
    ]
