# Generated by Django 4.2.16 on 2025-04-10 14:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('academic_main', '0001_initial'),
        ('assignments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentassignmentrecord',
            name='term',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assignment_records', to='academic_main.term'),
        ),
    ]
