# Generated by Django 4.2.16 on 2025-04-17 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0002_alter_studentassignmentrecord_term'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
