# Generated by Django 5.1.7 on 2025-05-12 23:52

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic_main', '0003_activeterm_school_term_school'),
        ('principal', '0001_initial'),
        ('stu_main', '0012_teacher_salary'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentdiscount',
            name='academic_year',
            field=models.CharField(blank=True, max_length=9, null=True),
        ),
        migrations.AddField(
            model_name='studentdiscount',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='studentdiscount',
            name='discount_type',
            field=models.CharField(choices=[('percentage', 'Percentage'), ('fixed', 'Fixed Amount')], default='percentage', max_length=10),
        ),
        migrations.AddField(
            model_name='studentdiscount',
            name='discount_value',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='studentdiscount',
            name='is_active',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
        migrations.AddField(
            model_name='studentdiscount',
            name='reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='studentdiscount',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.CreateModel(
            name='FeeCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('is_recurring', models.BooleanField(default=False)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fee_categories', to='academic_main.school')),
            ],
            options={
                'verbose_name_plural': 'Fee Categories',
                'unique_together': {('name', 'school')},
            },
        ),
        migrations.AddField(
            model_name='studentdiscount',
            name='fee_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='student_discounts', to='principal.feecategory'),
        ),
        migrations.AlterUniqueTogether(
            name='studentdiscount',
            unique_together={('student', 'fee_category', 'term', 'academic_year')},
        ),
        migrations.RemoveField(
            model_name='studentdiscount',
            name='discount_amount',
        ),
    ]
