# Generated by Django 5.2.1 on 2025-05-18 14:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic_main', '0004_schoolpaymentinfo'),
        ('principal', '0003_feepayment'),
        ('stu_main', '0017_alter_student_parents'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feepayment',
            name='fee_category',
        ),
        migrations.AlterUniqueTogether(
            name='studentdiscount',
            unique_together={('student', 'term', 'academic_year')},
        ),
        migrations.AddField(
            model_name='additionalfee',
            name='term',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='additional_fees', to='academic_main.term'),
        ),
        migrations.AlterField(
            model_name='feepayment',
            name='additional_fee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='principal.additionalfee'),
        ),
        migrations.AlterField(
            model_name='studentdiscount',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.RemoveField(
            model_name='studentdiscount',
            name='fee_category',
        ),
        migrations.DeleteModel(
            name='FeeCategory',
        ),
    ]
