# Generated by Django 5.2.1 on 2025-05-18 17:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic_main', '0004_schoolpaymentinfo'),
        ('principal', '0004_remove_feepayment_fee_category_and_more'),
        ('stu_main', '0017_alter_student_parents'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='studentdiscount',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='feepayment',
            name='class_fee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='principal.classfee'),
        ),
        migrations.AddField(
            model_name='studentdiscount',
            name='school_class',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='discounts', to='stu_main.class'),
        ),
        migrations.AlterUniqueTogether(
            name='studentdiscount',
            unique_together={('student', 'term', 'academic_year', 'school_class')},
        ),
        migrations.AddConstraint(
            model_name='feepayment',
            constraint=models.UniqueConstraint(fields=('student', 'class_fee'), name='unique_class_fee_payment'),
        ),
        migrations.AddConstraint(
            model_name='feepayment',
            constraint=models.UniqueConstraint(fields=('student', 'additional_fee'), name='unique_additional_fee_payment'),
        ),
    ]
