# Generated by Django 5.2.1 on 2025-05-18 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0005_alter_studentdiscount_unique_together_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='additionalfee',
            name='term',
        ),
        migrations.RemoveField(
            model_name='classfee',
            name='term',
        ),
    ]
