# Generated by Django 5.1.7 on 2025-04-21 11:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academic_main', '0001_initial'),
        ('stu_main', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SubjectGradeSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_exam_score', models.FloatField(default=0)),
                ('external_exam_score', models.FloatField(default=0)),
                ('total_assignment_score', models.FloatField(default=0)),
                ('external_assignment_score', models.FloatField(default=0)),
                ('external_test_score', models.FloatField(default=0)),
                ('class_subject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='grade_summaries', to='stu_main.classsubject')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_grade_summaries', to=settings.AUTH_USER_MODEL)),
                ('term', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subject_grade_summaries', to='academic_main.term')),
            ],
        ),
    ]
