# Generated by Django 5.1.7 on 2025-04-22 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teacher_logic', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subjectgradesummary',
            name='total_assignment_score',
        ),
        migrations.RemoveField(
            model_name='subjectgradesummary',
            name='total_exam_score',
        ),
    ]
