# Generated by Django 5.1.7 on 2025-04-23 17:46

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic_main', '0001_initial'),
        ('stu_main', '0001_initial'),
        ('teacher_logic', '0002_remove_subjectgradesummary_total_assignment_score_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassGradeSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('average_score', models.FloatField()),
                ('rank', models.PositiveIntegerField()),
                ('total_students', models.PositiveIntegerField()),
                ('generated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_grade_summaries', to=settings.AUTH_USER_MODEL)),
                ('student_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grade_summaries', to='stu_main.class')),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_grade_summaries', to='academic_main.term')),
            ],
            options={
                'ordering': ['-average_score'],
                'unique_together': {('student', 'term', 'student_class')},
            },
        ),
    ]
