# Generated by Django 5.1.7 on 2025-04-24 07:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teacher_logic', '0003_classgradesummary'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classgradesummary',
            name='generated_at',
        ),
        migrations.RemoveField(
            model_name='classgradesummary',
            name='total_students',
        ),
    ]
