# Generated by Django 5.1.7 on 2025-04-24 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher_logic', '0004_remove_classgradesummary_generated_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classgradesummary',
            name='average_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='classgradesummary',
            name='rank',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
