# Generated by Django 5.2.1 on 2025-05-19 18:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic_main', '0005_schoolpaymentinfo_bank_code_and_more'),
        ('teacher_logic', '0005_alter_classgradesummary_average_score_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GradingPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam_weight', models.FloatField(default=60)),
                ('exam_internal_ratio', models.FloatField(default=50)),
                ('assignment_weight', models.FloatField(default=20)),
                ('assignment_internal_ratio', models.FloatField(default=50)),
                ('test_weight', models.FloatField(default=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grading_policy', to='academic_main.school')),
            ],
            options={
                'verbose_name_plural': 'Grading Policies',
            },
        ),
    ]
